<a href="https://colab.research.google.com/github/YushirohMurasakih/Linear-Algebra-58020/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from numpy.linalg import eig

In [3]:
##Example 1

A=np.array([[-1,3],[2,5]])
print(A)

inv_A=np.linalg.inv(A)
print(inv_A)

B=np.array([[0],[0]])
print(B)

X=np.dot(inv_A,B)
print(X)

[[-1  3]
 [ 2  5]]
[[-0.45454545  0.27272727]
 [ 0.18181818  0.09090909]]
[[0]
 [0]]
[[0.]
 [0.]]


In [4]:
#Example 2
A=np.array([[4,2,0],[6,6,6],[0,6,9]])
print(A)
s,t=np.linalg.eig(A)
print(s.round())
print(t.round())
c=np.dot(A,t.round())
print(c)

f=np.array([[-1],[-1],[-1]])
print(f)
g=np.dot(A,f)
print(g)


[[4 2 0]
 [6 6 6]
 [0 6 9]]
[-0.  5. 14.]
[[ 0.  1.  0.]
 [-1.  0.  1.]
 [ 1. -1.  1.]]
[[-2.  4.  2.]
 [ 0.  0. 12.]
 [ 3. -9. 15.]]
[[-1]
 [-1]
 [-1]]
[[ -6]
 [-18]
 [-15]]
