<a href="https://colab.research.google.com/github/YushirohMurasakih/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
from numpy.linalg import eig 

##Problem 1

In [10]:
studC = 19

studA = (studC - 6)
studB = (studC * 3)

print("Student A has ", studA)
print("Student B has ", studB)
print("Student C has ", studC)

Student A has  13
Student B has  57
Student C has  19


##Problem 2

In [14]:
A = np.array([[3,-1,1], [9,-3,3], [-12,4,-4]])
print("Matrix A", A)
inv_A = np.linalg.pinv(A)
print("Inv A", inv_A)
B = np.array([[5],[10],[-20]])
print("Matrix A", A)
X = np.dot(inv_A, B)
print("Dot", X)
C = np.dot(A, X)
print("Checking", C)

Matrix A [[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
Inv A [[ 0.01048951  0.03146853 -0.04195804]
 [-0.0034965  -0.01048951  0.01398601]
 [ 0.0034965   0.01048951 -0.01398601]]
Matrix A [[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
Dot [[ 1.20629371]
 [-0.4020979 ]
 [ 0.4020979 ]]
Checking [[  4.42307692]
 [ 13.26923077]
 [-17.69230769]]


##Problem 3

In [6]:
matrix3 =np.array ([[8,5,-6],[-12,-9,-12],[-3,-3,5]]) #This line determines the array that will be solved
print(matrix3)

value,vector = np.linalg.eig(matrix3)   #This line contains the code for finding the eigenvalue and eigevector
print ("The eigenvalue/s is/are:",value)
print ("The eigenvectors are:",vector)

[[  8   5  -6]
 [-12  -9 -12]
 [ -3  -3   5]]
The eigenvalue/s is/are: [-8.11684397  3.          9.11684397]
The eigenvectors are: [[ 2.35632155e-01 -7.07106781e-01 -8.61671223e-01]
 [-9.57707415e-01  7.07106781e-01  2.99299241e-01]
 [-1.65148399e-01 -1.19155502e-16  4.09808086e-01]]
