<a href="https://colab.research.google.com/github/YushirohMurasakih/Linear-Algebra-58020/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

##Matrix Algebra

In [5]:
A = np.array([[1,2],[4,7]])
invA=(np.linalg.inv(A))
print(invA)

[[-7.  2.]
 [ 4. -1.]]


In [6]:
C = np.dot(A,invA)
print(C)

[[1. 0.]
 [0. 1.]]


##Program that applies the inverse of a 3x3 Matrix

In [55]:
B = np.array([[8,9,5],[3,4,2],[4,5,3]])
invB = np.linalg.inv(B)
print(invB)

[[ 1.  -1.  -1. ]
 [-0.5  2.  -0.5]
 [-0.5 -2.   2.5]]


In [56]:
C= np.dot(B,invB) #Checking for the theorem
print(C)

[[ 1.0000000e+00 -4.4408921e-16  4.4408921e-16]
 [ 0.0000000e+00  1.0000000e+00  8.8817842e-16]
 [ 0.0000000e+00 -4.4408921e-16  1.0000000e+00]]


##Transpose of the 3x3 Matrix

In [59]:
D = np.transpose(B)
print(D)

[[8 3 4]
 [9 4 5]
 [5 2 3]]


##Inverse of a 4x4 Matrix

In [66]:
E= np.array([[3,4,6,5],[9,8,3,2],[2,5,4,3],[5,8,4,6]])
print(E)

[[3 4 6 5]
 [9 8 3 2]
 [2 5 4 3]
 [5 8 4 6]]


In [67]:
F= np.linalg.inv(E)
print(F)

[[ 0.15652174  0.13913043 -0.32463768 -0.01449275]
 [-0.26956522 -0.0173913   0.37391304  0.04347826]
 [ 0.17391304  0.04347826  0.23188406 -0.27536232]
 [ 0.11304348 -0.12173913 -0.3826087   0.30434783]]


Transpose of the 4x4 Matrix

In [65]:
G= np.transpose(E)
print(E)

[[3 4 6 5]
 [9 8 3 2]
 [2 5 4 3]
 [5 8 4 6]]
