<a href="https://colab.research.google.com/github/YushirohMurasakih/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

##Question 1

In [2]:
A = np.eye(5) #this is a syntax that will display an identity matrix with a length of 5
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##Question 2

In [12]:
B1 = np.array([[3,4,6,5],[0,8,3,2],[0,0,4,3],[0,0,0,6]])
print(B1)

[[3 4 6 5]
 [0 8 3 2]
 [0 0 4 3]
 [0 0 0 6]]


##Question 3

In [11]:
B2 = np.array([[1,2,6],[2,8,4],[6,4,5]])
print(B2)

[[1 2 6]
 [2 8 4]
 [6 4 5]]


##Question 4

In [21]:
C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) #the given matrix C
print(C)

invC = np.linalg.inv(C) # this is the line that would convert matrix C to its inverse
print(" ")
print("Inverse")
print(" ")
print(invC)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
 
Inverse
 
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


#Question 5

In [23]:
C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) #the given matrix C the same in the previous number
print(C)

detC = np.linalg.det(C) # the command to solve the determinant
print(" ")
print("Determinant")
print(" ")
print(detC)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
 
Determinant
 
5.000000000000001


##Question 6

In [32]:
D = np.array([[5,4,1,3.4],[10,9,4,8.8],[10,13,15,19.2]]) ##this is the given matrix
print(D)

sqrtD = np.sqrt(D) # this line contains the command to find the roots of the given matrix
print(" ")
print("Roots")
print(" ")
print(sqrtD)

[[ 5.   4.   1.   3.4]
 [10.   9.   4.   8.8]
 [10.  13.  15.  19.2]]
 
Roots
 
[[2.23606798 2.         1.         1.84390889]
 [3.16227766 3.         2.         2.96647939]
 [3.16227766 3.60555128 3.87298335 4.38178046]]
