<a href="https://colab.research.google.com/github/YushirohMurasakih/Linear-Algebra-58020/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
a=np.array([[-5,0],[4,1]])
print(a)
b=np.array([[6,-3],[2,3]])
print(b)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]


In [5]:
print(a-b)

[[-11   3]
 [  2  -2]]


In [6]:
print(b-b)

[[0 0]
 [0 0]]
